data:
  password: A1a-zUuDrBtUS1Vt8nPO
  username: v-cert-cerma-app-y8fQU7ygCln7C3F
lease_duration: 3600
lease_id: v1.1/cermati/indodana/db/hosted/mysql/testenv/magento2/dev/creds/app/uKEAeRc8CzcbYXwG1tlTDD8C
renewable: true
request_id: f66982ef-f45e-4496-78af-6ccea86473ba
warnings: null
