data:
  password: A1a-vr2d395XraGrzzAt
  username: v-cert-cerma-app-EBdzaUsdA44c6vs
lease_duration: 3600
lease_id: v1.1/cermati/indodana/db/hosted/mysql/testenv/magento2/dev/creds/app/L75QWzIuM5izMSMlWgnlNc5q
renewable: true
request_id: ad987819-f258-e5ad-b317-1813912b873d
warnings: null
