# This playbook is used to generate a Vault role configuration script from a template
# $ANSIBLE_PLAYBOOK cloud/playbooks/cloud-aws-role-configure-template.yml
# Required extra variables:
#   - service_name                  = Name of the service
#   - service_environment           = Environment of the service
#   - binary_directory              = The directory of binary (e.g. vault, yq) which will be used in the Vault role configuration script 
#   - runtime_directory             = The directory of runtime configuration for the Vault role configuration
#   - vault_role_name               = Role name of the AWS Role on Vault (app, admin, readonly)
#   - organization                  = Name of the organization, used for constructing identifier
#   - team                          = Name of the team, used for constructing identifier
#   - product                       = Name of the product which use the service, used for constructing identifier
#   - cloudctl_vault_cert_file      = Full certificate path which will be used to authorize to Vault
#   - cloudctl_vault_key_file       = Full key file which will be used to authorize to Vault
#   - cloudctl_vault_ca_cert_file   = Full CA certificate path which will be used to authorize to Vault
#   - cloudctl_vault_token          = Valid Vault token to authorize to Vault
#   - aws_vault_access_key          = AWS access key for Vault
#   - aws_vault_access_secret_key   = AWS access secret key for Vault

---
- hosts: "localhost"
  
  roles:
    - role: "aws/common"

    - role: "aws/role/configure"