db:
  deployment: hosted
  hosted:
    db_host: "139.59.119.126"
    ssh_user: "root"
    db_provider_root_credential:
      username: root
      password_length: 32
secrets:
  vault:
    host: "https://vault.cermati.com:8443"
    tls: 
      enabled: true
      certs_bundle: dbctl-prod
