- block:
    - name: Configure Vault connection to AWS
      command: |
        vault write {{ aws_secrets_config.path }}/config/root
        access_key={{ aws_secrets_config.vault_iam_access_key }}
        secret_key={{ aws_secrets_config.vault_iam_secret_key }}
        region={{ aws_secrets_config.vault_iam_region }}

    - name: Map Vault named role to AWS role to assume
      command: |
        vault write {{ aws_secrets_config.path }}/roles/{{ item.role_name }}
        role_arns={{ item.role_arns | join(',') }}
        credential_type=assumed_role
      with_items:
        - "{{ aws_secrets_config.vault_roles }}"
  run_once: true