- name: Get list of initialized secrets engine endpoints
  command: vault secrets list -format yaml
  register: secrets_out

- name: Parse secrets engine endpoints list
  set_fact:
    secrets: "{{ secrets_out.stdout | from_yaml }}"

- name: Get endpoint existence
  set_fact:
    endpoint_existed: "{{ secrets[aws_secrets_config.path] is defined and secrets[aws_secrets_config.path]['type'] == 'aws' }}"

- name: Enable AWS Secrets Engine
  command: "vault secrets enable -path={{ aws_secrets_config.path }} aws"
  run_once: true
  when: not endpoint_existed