- name: Checking variables - DB Provider
  debug:
    var: db_provider

- name: Checking variables - DB Name
  debug:
    var: db_name

- name: Checking variables - DB Environment
  debug:
    var: db_environment

- name: Checking variables - DB Directory
  debug:
    var: db_directory

- name: Checking apsara Specification
  debug:
    var: db.apsara

- name: Ensure directory for terraform template
  file:
    path: "{{ db_directory }}/apsara"
    state: "directory"

- name: "Generate Random DB Password with length: {{ db.apsara.db_provider_root_credential.password_length }}"
  shell: "pwgen -s {{ db.apsara.db_provider_root_credential.password_length }} 1"
  register: db_generated_password_output

- name: Register
  set_fact:
    db_generated_password: "{{ db_generated_password_output.stdout_lines[0] }}"
    db_generated_user: "{{ db_name }}_{{ db.apsara.db_provider_root_credential.username }}"
    db_generated_migration_user: "{{ db_name }}_migrations"

- name: Constructing DB Apsara Terraform Template - main.tf
  template: 
    src: "apsara/terraform/tf.deploy-db-apsara.main.j2"
    dest: "{{ db_directory }}/main.tf"

- name: Constructing DB apsara Terraform Template - apsara/main.tf
  template: 
    src: "apsara/terraform/module/tf.deploy-db-apsara.module.main.j2"
    dest: "{{ db_directory }}/apsara/main.tf"

- name: Constructing DB apsara Terraform Template - apsara/outputs.tf
  template: 
    src: "apsara/terraform/module/tf.deploy-db-apsara.module.outputs.j2"
    dest: "{{ db_directory }}/apsara/outputs.tf"

- name: Constructing DB apsara Terraform Template - apsara/variables.tf
  template: 
    src: "apsara/terraform/module/tf.deploy-db-apsara.module.variables.j2"
    dest: "{{ db_directory }}/apsara/variables.tf"

- name: Constructing DB apsara tfapply
  template: 
    src: "apsara/terraform/tfapply.j2"
    dest: "{{ db_directory }}/tfapply"
    mode: 0755

- name: Constructing DB apsara tfdestroy
  template: 
    src: "apsara/terraform/tfdestroy.j2"
    dest: "{{ db_directory }}/tfdestroy"
    mode: 0755

- name: Constructing DB apsara generated-password.tfvars
  template:
    src: "apsara/terraform/generated-password.tfvars.j2"
    dest: "{{ db_directory }}/.generated-password.tfvars"

- name: Constructing DB MYSQLPASSWORD=generated_password
  template:
    src: "apsara/sql/MYSQLPASSWORD.j2"
    dest: "{{ db_directory }}/MYSQLPASSWORD"

- name: Constructing Secrets Management Flow - vault
  template:
    src: apsara/secrets/creds-upload-vault.j2
    dest: "{{ db_directory }}/.creds-upload-vault"
    mode: 0755

- name: Preparing SQL db directory
  file:
    path: "{{ db_directory }}/sql"
    state: directory

- name: Preparing db __roles__/migrations directory
  file:
    path: "{{ db_directory }}/sql/__roles__/migrations/"
    state: directory

- name: Constructing DB SQL creation script
  template:
    src: apsara/sql/create-db.sql.j2
    dest: "{{ db_directory }}/sql/create-db.sql"

- name: Constructing __roles__/migrations/creation.sql
  template:
    src: "apsara/sql/__roles__/migrations/creation.sql.j2"
    dest: "{{ db_directory }}/sql/__roles__/migrations/creation.sql"