data:
  password: A1a-VP9vslruPgeOK4yQ
  username: v-cert-cerma-app-9aN7Fr6BU79hWPl
lease_duration: 3600
lease_id: v1.1/cermati/indodana/db/hosted/mysql/testenv/prestashop/dev/creds/app/plrPJfyoswfwMENquF6rwjpN
renewable: true
request_id: 9a83b23c-9e90-b07d-e5ec-43670d52c1aa
warnings: null
