- name: Import
  debug:
    msg: "{{ db_engine }} | {{ db_provider }} | {{ db_name }} | {{ db_environment }}"

- name: Blueprint Directory
  debug:
    msg: "{{ db_blueprint_directory }}"

- name: Set DB deployment
  set_fact:
    db_deployment: "{{ db_provider }}"

- name: Override local db_provider
  set_fact:
    db_deployment: "hosted"
  when: "db_provider == 'local'"

- name: db-deployment
  debug:
    var: db_deployment

- name: Setting Variables
  set_fact:
    db_identifier: "db|{{ db_deployment }}|{{ db_engine }}|{{ organization }}|{{ team }}|{{ product }}|{{ db_name }}|{{ db_environment }}" 
    db_identifier_path: "db|{{ db_deployment }}|{{ db_engine }}|{{ organization }}|{{ team }}|{{ product }}|{{ db_name }}|{{ db_environment }}" 

- name: DB Identifier
  set_fact:
    db_identifier: "{{ db_identifier | replace('|','-') }}"

- name: DB Identifier
  set_fact:
    db_identifier: "{{ db_identifier | replace('_','-') }}"

- name: DB Identifier - Debug
  debug:
    var: db_identifier

- name: DB Identifier Path
  set_fact:
    db_identifier_path: "{{ db_identifier_path | replace('|','/') }}"

- name: DB Identifier Path - Debug
  debug:
    var: db_identifier_path

- name: db-bootstrap-file
  debug:
    msg: "{{ db_bootstrap_file }}"

- name: Reading db-bootstrap-file
  include_vars: "{{ db_bootstrap_file }}"

- name: Reading db-deploy-file
  include_vars: "{{ db_deploy_file }}"
  when: "db_provider == 'rds'"

- name: "DB Host"
  debug:
    var: db_host

- name: Create specification yml
  template:
    src: spec.yml.j2
    dest: "{{ db_blueprint_directory }}/{{ db_environment }}.yml"

- name: Create tfimport
  template:
    src: rds/terraform/tfimport.j2
    dest: "{{ db_import_directory }}/tfimport"
    mode: 0755
  when: "db_provider == 'rds'"

- name: Create resource import
  template: 
    src: rds/terraform/module/tf.import-db-rds.module.main.j2
    dest: "{{ db_import_directory }}/rds/main.tf"
  when: "db_provider == 'rds'"

- name: Create terraform import
  template: 
    src: rds/terraform/tf.import-db-rds.main.j2
    dest: "{{ db_import_directory }}/import.tf"
  when: "db_provider == 'rds'"

- name: Create app __roles__
  template: 
    src: __roles__/app.creation.sql.j2
    dest: "{{ db_import_roles_directory }}/{{ db_environment }}/app/creation.sql"

- name: Create dba __roles__
  template: 
    src: __roles__/dba.creation.sql.j2
    dest: "{{ db_import_roles_directory }}/{{ db_environment }}/dba/creation.sql"

- name: Create migrations __roles__
  template: 
    src: __roles__/migrations.creation.sql.j2
    dest: "{{ db_import_roles_directory }}/{{ db_environment }}/migrations/creation.sql"

- name: Create readonly __roles__
  template: 
    src: __roles__/readonly.creation.sql.j2
    dest: "{{ db_import_roles_directory }}/{{ db_environment }}/readonly/creation.sql"