- hosts: "{{ blueprint }}"
  
  vars_files: 
    - "{{ blueprint_file }}"
    
  tasks:
    - name: Get CA public key
      shell:
        cmd: |
          vault read -field=public_key {{ ssh_secrets_config.path }}/config/ca > /tmp/trusted-ca-keys-{{ host_group_target }}.pem

    - name: Fetch CA public key
      fetch:
        src: "/tmp/trusted-ca-keys-{{ host_group_target }}.pem"
        dest: "{{ temp_dir }}/trusted-ca-keys-{{ host_group_target }}.pem"
        mode: 0664
        flat: yes
  run_once: true

- hosts: "{{ host_group_target }}"
  become: true

  vars:
    trusted_ca_dir: "/etc/ssh/trusted-ca-keys-{{ host_group_target }}.pem"

  tasks:
    - name: Copy CA public key to target hosts
      copy:
        src: "{{ temp_dir }}/trusted-ca-keys-{{ host_group_target }}.pem"
        dest: "{{ trusted_ca_dir }}"
    
    - name: Append or Update if TrustedUserCAKeys config existed SSH config
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^TrustedUserCAKeys '
        state: present
        line: "TrustedUserCAKeys {{ trusted_ca_dir }}"
      register: is_ca_config_existed
      ignore_errors: true

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted