- name: CSR details
  debug:
    var: csr

- block:
    - name: Setting variable
      set_fact:
        csr_directory: "/usr/share/pki/certs/member/{{ member }}@{{ device_identifier }}@{{ blueprint }}"

    - name: Ensure directory
      file:
        path: "{{ csr_directory }}"
        state: directory

    - name: Create CSR
      template:
        src: csr.conf.j2
        dest: "{{ csr_directory }}/csr.conf"

    - name: Create generate
      template:
        src: generate.j2
        dest: "{{ csr_directory }}/generate"
        mode: 0755

    - name: Create view
      template:
        src: view.j2
        dest: "{{ csr_directory }}/view"
        mode: 0755

    - name: Execute generate
      command: "./generate"
      args:
        chdir: "{{ csr_directory }}"
  become: true