- block:
    - name: etcd Download
      get_url:
        url: "{{ etcd_release_url }}/{{ installer.version }}/{{ etcd_package }}.tar.gz"
        dest: "{{ etcd_install_directory }}/{{ etcd_package }}.tar.gz"
        mode: 0755

    - name: Extract etcd
      shell: "tar xzvf {{ etcd_install_directory }}/{{ etcd_package }}.tar.gz -C {{ etcd_install_directory }}/etcd --strip-components=1"

    - name: Copy Binary etcd
      copy:
        src: "{{ etcd_install_directory }}/etcd/etcd"
        dest: "{{ etcd_binary_directory }}/etcd"
        mode: 0755
        owner: "{{ etcd_user }}"
        group: "{{ etcd_user }}"
        remote_src: true

    - name: Copy Binary etcdctl
      copy:
        src: "{{ etcd_install_directory }}/etcd/etcdctl"
        dest: "{{ etcd_binary_directory }}/etcdctl"
        mode: 0755
        owner: "{{ etcd_user }}"
        group: "{{ etcd_user }}"
        remote_src: true

    - name: Create etcdctl wrapper
      template:
        src: "etcdctl.j2"
        dest: "/usr/bin/etcdctl"
        mode: 0755
  become: true