- name: Deploy etcd
  debug:
    msg: "etcd-deployment : {{ cluster }} - {{ blueprint }}"

- name: Download and Install etcd
  include_tasks: "install.yml"

- block:
    - name: Create etcd configuration file
      template:
        src: etcd-conf.yml.j2
        dest: "{{ etcd_config_directory }}/{{ etcd_conf_file }}"
        mode: 0644
        owner: "{{ etcd_user }}"
        group: "{{ etcd_group }}"      

    - name: Create etcd systemd file
      template:
        src: etcd-systemd-script.j2
        dest: "/lib/systemd/system/{{ target }}.service"
        mode: 0644

    - name: Create etcd logrotate configuration file
      template:
        src: etcd-logrotate.j2
        dest: "/etc/logrotate.d/{{ target }}"
        mode: 0644

    - name: Restart systemd etcd
      systemd:
        name: "{{ target }}"
        state: "restarted"
        enabled: yes
  become: true