data:
  password: A1a-K8VFpvpwE7LYD5Li
  username: v-cert-cerma-app-QU1ZzNplgC4kIau
lease_duration: 3600
lease_id: v1.1/cermati/indodana/db/hosted/mysql/testenv/woocommerce/dev/creds/app/SfsKgtPjkuSSG5uIy71iC872
renewable: true
request_id: 465495b3-02ed-9fa0-17c5-c6ef60d0a9bf
warnings: null
