- block:
    - name: Configure Vault CA SSH keys
      command: |
        vault write {{ ssh_secrets_config.path }}/config/ca
        public_key={{ vault_ca_ssh_public_key }}
        private_key={{ vault_ca_ssh_private_key }}
      when: not ssh_secrets_config.generate_signing_key and not endpoint_existed

    - name: Configure Vault CA SSH keys and let Vault generate the key pairs
      command: |
        vault write {{ ssh_secrets_config.path }}/config/ca generate_signing_key=true
      when: ssh_secrets_config.generate_signing_key and not endpoint_existed

    - name: Attach SSH options to Vault named role 
      shell:
        cmd: |
          vault write {{ ssh_secrets_config.path }}/roles/{{ item.role_name }} -<<EOH
            {{ item.role_options | to_json }}
          EOH
      with_items:
        - "{{ ssh_secrets_config.vault_roles }}"
  run_once: true