- name: Get list of initialized secrets engine endpoints
  command: vault secrets list -format yaml
  register: secrets_out

- name: Parse secrets engine endpoints list
  set_fact:
    secrets: "{{ secrets_out.stdout | from_yaml }}"

- name: Get endpoint status
  set_fact:
    endpoint_existed: "{{ secrets[ssh_secrets_config.path] is defined and secrets[ssh_secrets_config.path]['type'] == 'ssh' }}"

- name: Enable SSH Secrets Engine
  command: "vault secrets enable -path={{ ssh_secrets_config.path }} ssh"
  run_once: true
  when: not endpoint_existed