- name: Get list of initialized secrets engine endpoints
  command: vault secrets list -format yaml
  register: secrets_out

- name: Parse secrets engine endpoints list
  set_fact:
    secrets: "{{ secrets_out.stdout | from_yaml }}"

- name: Get endpoint existence
  set_fact:
    endpoint_existed: "{{ secrets[kv_secrets_config.path] is defined and secrets[kv_secrets_config.path]['type'] == 'kv' }}"

- name: Enable KV Secrets Engine
  command: "vault secrets enable -path={{ kv_secrets_config.path }} -version={{ kv_secrets_config.version }} kv"
  run_once: true
  when: not endpoint_existed