db:
  deployment: hosted
  hosted:
    db_host: "localhost"
    db_provider_root_credential:
      username: root
      password_length: 32
secrets:
  vault:
    host: "https://localhost:8200"
    tls: 
      enabled: true
      certs_bundle: dbctl-dev
