- name: Deploy Vault
  debug:
    msg: "vault-deployment : {{ cluster }} - {{ blueprint }}"

- name: Download and Install Vault
  include_tasks: "install.yml"

- block:
    - name: Create Vault listener configuration file
      template:
        src: "vault-listener-{{ member.backend }}.hcl.j2"
        dest: "{{ item }}"
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
      with_items: 
        - "{{ vault_config_directory }}/{{ target }}.hcl"

    - name: Create Vault systemd file
      template:
        src: vault-systemd-script.j2
        dest: "{{ item }}"
        mode: 0644
      with_items:
        - "/lib/systemd/system/{{ target }}.service"

    - name: Create vault logrotate configuration
      template:
        src: vault-logrotate.j2
        dest: "{{ item }}"
        mode: 0644
      with_items:
        - "/etc/logrotate.d/{{ target }}"

    - name: Restart systemd vault
      systemd:
        name: "{{ target }}"
        state: "restarted"
        enabled: yes
  become: true