data:
  password: A1a-BQolfAOedOc8JXqZ
  username: v-cert-cerma-app-bjK7iYGEifhAGpH
lease_duration: 3600
lease_id: v1.1/cermati/indodana/db/hosted/mysql/testenv/opencartv2/dev/creds/app/59gmsKqXYN5KBG8ernXGUaAU
renewable: true
request_id: 4b8a374a-a35a-5d0e-3526-70f9e73b4e6b
warnings: null
