- block:
    - name: "Prepare allowed roles"
      set_fact:
        "{{ item }}_roles" : "{{ database_secrets_config.vault_roles | map('regex_replace', '(.*)', '\\1-' + item) | join(',') }}"
      with_items:
        - "{{ database_secrets_config.db_names }}"

    - name: Configure Vault connection to Database
      command: |
        vault write {{ database_secrets_config.path }}/config/{{ item }}
        plugin_name={{ database_secrets_config.plugin_name }}
        allowed_roles={{ vars[item + "_roles"] }}
        connection_url={{ database_secrets_config.connection_url }}/{{ item }}
        username={{ database_secrets_config.vault_db_username }}
        password={{ database_secrets_config.vault_db_password }}
      with_items:
        - "{{ database_secrets_config.db_names }}"

    - name: Map Vault named role to SQL statements
      command: |
        vault write {{ database_secrets_config.path }}/roles/{{ item[0] }}-{{ item[1] }} \
        db_name={{ item[1] }} \
        creation_statements="{{ lookup('template','{{ statements_directory }}/{{ item[0] }}-creation.sql.j2') }}" \
        revocation_statements="{{ lookup('template','{{ statements_directory }}/{{ item[0] }}-revocation.sql.j2') }}" \
        default_ttl={{ database_secrets_config.default_ttl }} \
        max_ttl={{ database_secrets_config.max_ttl }}
      with_nested:
        - "{{ database_secrets_config.vault_roles }}"
        - "{{ database_secrets_config.db_names }}"
  run_once: true