- name: Get list of initialized secrets engine endpoints
  command: vault secrets list -format yaml
  register: secrets_out

- name: Parse secrets engine endpoints list
  set_fact:
    secrets: "{{ secrets_out.stdout | from_yaml }}"

- name: Get endpoint existence
  set_fact:
    endpoint_existed: "{{ secrets[database_secrets_config.path] is defined and secrets[database_secrets_config.path]['type'] == 'database' }}"

- name: Enable Database Secrets Engine
  command: "vault secrets enable -path={{ database_secrets_config.path }} database"
  run_once: true
  when: not endpoint_existed