- name: Signing certificate process
  debug:
    msg: "{{ member_cert }} signed by: {{ ca_server }}-{{ ca_target }}"

- name: Preparing variables
  set_fact:
    pkictl_directory: "/usr/share/pki"
    pkictl_ca_directory: "/usr/share/pki/pki"
    csr_type: member
    csr_target: "{{ member_cert }}"
    
- name: Setting directory
  set_fact:
    csr_directory: "{{ member }}"
    csr_file: "{{ member_cert }}.csr"
    csr_remote_directory: "{{ pkictl_directory }}/certs/{{ csr_type }}/{{ csr_target }}"
    crt_directory: "{{ member }}"
    crt_file: "{{ member_cert }}.crt"
    crt_remote_directory: "{{ pkictl_directory }}/certs/{{ csr_type }}/{{ csr_target }}"
    crt_ca_chain_file: "{{ member_cert }}-ca-chain.crt"

- block:
    - name: Ensure csr_remote_directory
      file:
        path: "{{ csr_remote_directory }}"
        state: directory

    - name: Sending csr to CA Server
      copy:
        src: "{{ csr }}"
        dest: "{{ csr_remote_directory }}/{{ csr_file }}"

    - name: Sign the CSR (in remote)
      command: "./pki-sign-csr {{ csr_type }} {{ csr_target }} {{ ca_target }}"
      args:
        chdir: "{{ pkictl_directory }}"
    
    - name: Retrieve crt
      fetch:
        src: "{{ crt_remote_directory }}/{{ crt_file }}"
        dest: "{{ crt }}"
        mode: 0644
        flat: yes

    - name: Retrieve ca-chain.crt
      fetch:
        src: "{{ pkictl_ca_directory }}/{{ ca_target }}/ca-chain.crt"
        dest: "{{ ca_crt }}"
        mode: 0644
        flat: yes

    - name: Retrieve cert-ca-chain.crt
      fetch:
        src: "{{ crt_remote_directory }}/{{ crt_ca_chain_file }}"
        dest: "{{ crt_ca_chain }}"
        mode: 0644
        flat: yes
  become: true