- name: Welcome to etcd cluster provisioning
  debug:
    msg: 'Provision blueprint: {{ cluster }} - {{ blueprint }}'

- name: etcd Cluster specifications
  debug:
    var: "etcd_cluster"

- name: Setting prefix
  set_fact:
    prefix: ""

- name: Setting prefix
  set_fact:
    prefix: "{{ etcd_cluster.options.prefix + '-' }}"
  when: "etcd_cluster.options.prefix != ''"

- name: Populate target
  set_fact:
    target: "{{ inventory_hostname | replace(prefix,'') | replace(etcd_cluster.domain, '') }}"

- name: Reading member cluster specification
  set_fact:
    member: "{{ etcd_cluster.members[target] }}"

- name: Member Specification
  debug:
    var: member

- name: Machine IP
  set_fact:
    machine_ip: "{{ ansible_default_ipv4.address }}"
  when: "etcd_cluster.environment != 'development'"

- set_fact:
    machine_ip: "127.0.0.1"
  when: "etcd_cluster.environment == 'development'"

- name: Machine IP
  debug:
    var: machine_ip

- name: Set variables
  set_fact:
    etcd_base_directory: "/opt/etcd"
    etcd_binary_directory: "/opt/etcd/bin"
    etcd_install_directory: "/opt/etcd/.install/{{ target }}"
    etcd_data_directory: "/opt/etcd/data"
    etcd_config_directory: "/etc/etcd/conf.d"
    etcd_conf_file: "{{ target }}.conf.yml"
    etcd_log_directory: "/var/log/etcd"
    etcd_release_url: "https://github.com/coreos/etcd/releases/download/"
    etcd_package: "etcd-{{ installer.version }}-{{ installer.os }}-{{ installer.arch }}"
    etcd_tls_directory: "/etc/etcd/tls"

- block:
    - name: "Add etcd group"
      group:
        name: "{{ etcd_group }}"
        state: present
        system: yes

    - name: "Add etcd user"
      user:
        name: "{{ etcd_user }}"
        group: "{{ etcd_group }}"
        system: yes

    - name: Ensure directory
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ etcd_user }}"
        group: "{{ etcd_group }}"
      with_items:
        - "{{ etcd_base_directory }}"
        - "{{ etcd_binary_directory }}"
        - "{{ etcd_install_directory }}"
        - "{{ etcd_install_directory }}/etcd"
        - "{{ etcd_data_directory }}"
        - "{{ etcd_data_directory }}/{{ member.data_dir }}"
        - "{{ etcd_config_directory }}"
        - "{{ etcd_log_directory }}"
        - "{{ etcd_tls_directory }}"
  become: true