data:
  password: A1a-vn0gNtISPVRakbT7
  username: v-cert-cerma-app-W9CzZhkQ1UfoHTB
lease_duration: 3600
lease_id: v1.1/cermati/indodana/db/hosted/mysql/testenv/magento1/dev/creds/app/lNWfDctFKFW3ADpf57yPnjGO
renewable: true
request_id: 235347b0-7eac-498c-fcfb-eb36b50f2efd
warnings: null
